function pr3_3_plot3rdPolyTransformBorder(w, xlow, xupp, ylow, yupp)

syms x1 x2;
printString = [num2str(w(1)), '+',...
               num2str(w(2)), '*x1 +',...
               num2str(w(3)), '*x2 +',...
               num2str(w(4)), '*x1^2 +',...
               num2str(w(5)), '*x1*x2 +',...
               num2str(w(6)), '*x2^2 +',...
               num2str(w(7)), '*x1^3 +',...
               num2str(w(8)), '*x1^2*x2 +',...
               num2str(w(8)), '*x1*x2^2 +',...
               num2str(w(10)), '*x2^3 = 0'];
           
ezplot(printString, [xlow, xupp, ylow, yupp]);
              
               
               

axis([xlow xupp ylow yupp]);

end

